spring.application.name=journal-app
spring.data.mongodb.auto-index-creation=true

# localdb
# spring.data.mongodb.uri=mongodb://localhost:27017
# spring.data.mongodb.database=journaldb

# remote db credentials directly here
# MONGODB_URI=mongodb+srv://<username>:<password>@<cluster>/
# MONGODB_DATABASE=journaldb

# fetching remote db credentials from .env file
spring.config.import=optional:file:.env[.properties]
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE:journaldb}

# The optional: import lets production run without a .env file, as long as MONGODB_URI is supplied by the deployment environment.